version: '3.9'

services:
 
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env 
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: