version: '3.9'

services:
 
  db:
    image: postgres
    # restart: always
    environment:
      - POSTGRES_DB=taxi-tandil-dev
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    env_file:
      - .env 
    volumes:
      - /mnt/pg-volume:/var/lib/postgresql/data
 
  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
 
# volumes:
#   pgdata: